In [91]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy.io as sio
import scipy.stats as ss
from pyitlib import discrete_random_variable as drv

In [33]:
# load your data (don't touch, just run)

"""
data = []
f = open('covtype.data','r')
while(1):
    line = f.readline()
    if  len(line) < 100:
        print line
    
    if len(line) == 0: break
    data.append(np.array([float(k) for k in line.split(',')]))
    if len(data) % 100000 == 0:
        print len(data)
        
f.close
data = np.vstack(data)
N = data.shape[0]
idx = np.random.permutation(N)


X_test = data[:N/5,:]
X_train = data[N/5:,:]
y_test = X_test[:,-1]
y_train = X_train[:,-1]
X_test = X_test[:,:-1]
X_train = X_train[:,:-1]


sio.savemat('covtype.mat',{'X_train':X_train,'X_test':X_test,'y_train':y_train,'y_test':y_test})
data = sio.loadmat('covtype.mat')
X_train = data['X_train'][:100,:]
X_test = data['X_test'][:100,:]
y_train = data['y_train'][0][:100]
y_test = data['y_test'][0][:100]
print X_train.shape, X_test.shape, y_train.shape, y_test.shape
sio.savemat('covtype_reduced.mat',{'X_train':X_train,'X_test':X_test,'y_train':y_train,'y_test':y_test})
"""




data = sio.loadmat('covtype_reduced.mat')
X_train = data['X_train']
X_test = data['X_test']
y_train = data['y_train'][0]
y_test = data['y_test'][0]

print(np.unique(y_train), np.unique(y_test))

print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)


[1. 2. 3. 4. 5. 6. 7.] [1. 2. 3. 4. 5. 6. 7.]
(468, 54) (116202, 54) (468,) (116202,)


In [101]:
def entropy(y):
    if len(y) == 0:
        return 0
    unique, count = np.unique(y, return_counts=True, axis=0)
    individualProbabilities = count/len(y)
    entropy = -np.sum(individualProbabilities*np.log2(individualProbabilities))
    return entropy


#Additional Helper function
def jointEntropy(y,x):
    yx = np.c_[y,x]
    print(entropy(yx))
    return entropy(yx)

def cond_entropy(y,yhat):
    return jointEntropy(y,yhat) - entropy(yhat)

random_sequences = sio.loadmat('random_sequences.mat')

s1 = random_sequences['s1'][0]
s2 = random_sequences['s2'][0]

print ('entropy = ', entropy(s1))
print ('conditional entropy = ', cond_entropy(s1,s2))

## Verification
print("verification entropy = :",drv.entropy(s1))
print("verification conditional entropy = :",drv.entropy_conditional(s1,s2))

entropy =  3.3141823231610834
4.301297258135399
conditional entropy =  3.3029598816135173
verification entropy = : 3.3141823231610834
verification conditional entropy = : 3.3029598816135173


In [74]:
from scipy.stats import entropy as ww
s1 = random_sequences['s1'][0]
s2 = random_sequences['s2'][0]
unique, count = np.unique(s1, return_counts=True, axis=0)
individualProbabilities = count/len(s1)

unique2, count2 = np.unique(s2, return_counts=True, axis=0)
individualProbabilities2 = count2/len(s2)
ww(individualProbabilities, base=2)


ww(individualProbabilities,base=2)

3.314182323161083

In [76]:
print(individualProbabilities)

[0.091 0.09  0.112 0.101 0.108 0.106 0.113 0.092 0.081 0.106]


In [75]:
print(individualProbabilities2)

[0.476 0.524]


In [41]:
a = np.c_[s1,s2]
np.shape(a)

(1000, 2)

In [7]:
s1 = []
s2 = []

print ('entropy = ', entropy(s1))
print ('conditional entropy = ', cond_entropy(s1,s2))

entropy =  0
conditional entropy =  0


In [22]:
a = pd.DataFrame(X_train)
pd.options.display.max_columns = a.shape[1]
a.describe(include = 'all')

0           1           2           3           4  \
count   100.000000  100.000000  100.000000  100.000000  100.000000   
mean   2954.710000  153.970000   13.910000  281.230000   59.470000   
std     275.496991  110.024557    7.294795  192.987248   74.211744   
min    2070.000000    8.000000    1.000000    0.000000  -26.000000   
25%    2767.500000   59.750000    9.000000  120.000000    2.750000   
50%    2993.500000  116.500000   12.500000  242.000000   28.500000   
75%    3161.500000  248.250000   18.000000  422.000000   91.500000   
max    3447.000000  357.000000   35.000000  787.000000  276.000000   

                 5           6           7          8            9  \
count   100.000000  100.000000  100.000000  100.00000   100.000000   
mean   1973.400000  214.690000  223.650000  139.70000  1813.120000   
std    1393.970189   26.634714   17.046801   39.77703  1153.419451   
min      30.000000  112.000000  167.000000    0.00000   201.000000   
25%    1010.250000  201.750000  215.750000  117.00000  1013.500000   
50%    1698.500000  220.500000  223.500000  142.00000  1481.000000   
75%    2716.750000  232.250000  234.250000  169.25000  2350.500000   
max    6166.000000  254.000000  254.000000  239.00000  6610.000000   

               10          11          12          13      14          15  \
count  100.000000  100.000000  100.000000  100.000000  100.00  100.000000   
mean     0.400000    0.060000    0.490000    0.050000    0.01    0.020000   
std      0.492366    0.238683    0.502418    0.219043    0.10    0.140705   
min      0.000000    0.000000    0.000000    0.000000    0.00    0.000000   
25%      0.000000    0.000000    0.000000    0.000000    0.00    0.000000   
50%      0.000000    0.000000    0.000000    0.000000    0.00    0.000000   
75%      1.000000    0.000000    1.000000    0.000000    0.00    0.000000   
max      1.000000    1.000000    1.000000    1.000000    1.00    1.000000   

          16      17     18          19     20     21     22          23  \
count  100.0  100.00  100.0  100.000000  100.0  100.0  100.0  100.000000   
mean     0.0    0.01    0.0    0.020000    0.0    0.0    0.0    0.050000   
std      0.0    0.10    0.0    0.140705    0.0    0.0    0.0    0.219043   
min      0.0    0.00    0.0    0.000000    0.0    0.0    0.0    0.000000   
25%      0.0    0.00    0.0    0.000000    0.0    0.0    0.0    0.000000   
50%      0.0    0.00    0.0    0.000000    0.0    0.0    0.0    0.000000   
75%      0.0    0.00    0.0    0.000000    0.0    0.0    0.0    0.000000   
max      0.0    1.00    0.0    1.000000    0.0    0.0    0.0    1.000000   

           24         25          26     27     28     29      30      31  \
count  100.00  100.00000  100.000000  100.0  100.0  100.0  100.00  100.00   
mean     0.01    0.08000    0.060000    0.0    0.0    0.0    0.01    0.01   
std      0.10    0.27266    0.238683    0.0    0.0    0.0    0.10    0.10   
min      0.00    0.00000    0.000000    0.0    0.0    0.0    0.00    0.00   
25%      0.00    0.00000    0.000000    0.0    0.0    0.0    0.00    0.00   
50%      0.00    0.00000    0.000000    0.0    0.0    0.0    0.00    0.00   
75%      0.00    0.00000    0.000000    0.0    0.0    0.0    0.00    0.00   
max      1.00    1.00000    1.000000    0.0    0.0    0.0    1.00    1.00   

           32          33     34          35          36          37      38  \
count  100.00  100.000000  100.0  100.000000  100.000000  100.000000  100.00   
mean     0.01    0.020000    0.0    0.050000    0.100000    0.040000    0.01   
std      0.10    0.140705    0.0    0.219043    0.301511    0.196946    0.10   
min      0.00    0.000000    0.0    0.000000    0.000000    0.000000    0.00   
25%      0.00    0.000000    0.0    0.000000    0.000000    0.000000    0.00   
50%      0.00    0.000000    0.0    0.000000    0.000000    0.000000    0.00   
75%      0.00    0.000000    0.0    0.000000    0.000000    0.000000    0.00   
max      1.00    1.000000    0.0    1.0000

In [29]:
np.shape(X_train[:,12])

(100,)

In [31]:
np.unique(X_train[:,1], return_counts=True, axis=0)

(array([  8.,  12.,  14.,  18.,  20.,  21.,  22.,  27.,  28.,  33.,  34.,
         40.,  41.,  42.,  50.,  51.,  52.,  53.,  56.,  59.,  60.,  62.,
         65.,  68.,  74.,  75.,  79.,  81.,  83.,  88.,  90.,  91.,  93.,
         96.,  98., 100., 104., 106., 111., 112., 116., 117., 118., 124.,
        129., 135., 137., 139., 152., 154., 158., 166., 171., 183., 189.,
        197., 199., 202., 206., 225., 227., 228., 229., 243., 264., 276.,
        280., 282., 287., 288., 289., 307., 308., 312., 314., 322., 329.,
        330., 335., 337., 338., 351., 354., 355., 357.]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2, 2, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1,
        1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 3, 1, 1, 1, 1, 1, 1]))

In [12]:
def _find_best_split(X, y, max_features):
    """Greedy algorithm to find the best feature and value for a split"""
    subset = np.random.choice(X.shape[1], max_features, replace = False)    
    max_col, max_val, max_gain = None, None, None
    parent_entropy = _compute_entropy(y)

    for column in subset:
        split_values = _find_splits(X, column)
        for value in split_values:
            splits = _split(X, y, column, value, return_X = False)
            gain = parent_entropy - _compute_splits_entropy(y, splits)

            if max_gain is None or gain > max_gain:
                max_col, max_val, max_gain = column, value, gain

    return max_col, max_val, max_gain




def find_best_split(x,y):
    columns = np.shape[1]
    for column in range(columns):
        
    
    best_feat = 0
    splitval = 0.
    set1 = range(len(y)//2)
    set2 = range(len(y)//2,len(y))
    return best_feat, splitval, set1, set2

def _compute_entropy(split):
    """entropy score using a fix log base 2"""
    _, counts = np.unique(split, return_counts = True)
    p = counts / split.shape[0]
    entropy = -np.sum(p * np.log2(p))
    return entropy


best_feat, splitval, set1, set2 = find_best_split(X_train, y_train)
y_new = y_train * 0
y_new[set1] = 1
print ('information gained in first step', entropy(y_train) - cond_entropy(y_train,y_new))

information gained in first step 0.7664606047746445


In [22]:
def purity(y):
    return ss.mode(y)[1]/len(y+0.)
    
class Node:
    def __init__(self,  sample_idx, nodeid,  is_leaf = True):
        self.is_leaf = is_leaf
        self.id = nodeid
        self.sample_idx = sample_idx
        self.children = []
        
        
        
    def visit_node(self, x):
        if self.is_leaf:
            return self.label
        """ Fill me in """
        return self.children[0].visit_node(x)
        
    def add_split_details(self, splitfeat, splitval)  :
        self.splitfeat = splitfeat
        self.splitval = splitval
    
        
class Tree:
    def __init__(self, x,y):
        m = len(y)
        self.x = x
        self.y = y
        self.maxid = -1
        self.root = self.construct_node(np.array(range(m)))
        self.leaves = [self.root]
        
    def print_tree(self):
        print ('printing tree...')
        def print_node(parent, node):
            print (node.id, )
            
            if parent is not None:
                print(', parent ', parent.id,)
            else:
                print(', ROOT', )
                 
            print(', label ', node.label,)
            if node.is_leaf: 
                print(', LEAF, ', 'nsamples %d, purity %.2f' %(len(node.sample_idx), purity(self.y[node.sample_idx])))
            else:
                print(', NONLEAF, split %d, val %.2f' % (node.splitfeat, node.splitval))
            if not node.is_leaf:
                for ch in node.children:
                    print_node(node, ch)
        print_node(None, self.root)
        
        
    def construct_node(self, sample_idx):
        node = Node(sample_idx, self.maxid + 1,  True)
        node.label = 0 # fill me in
        node.entropy = entropy(self.y[sample_idx])
        node.num_mistakes = np.sum(np.not_equal(node.label, self.y[sample_idx]))
        self.maxid += 1
        return node
        


    def report_train_err(self):
        total_mistakes = 0
        for leaf in self.leaves:
            total_mistakes += leaf.num_mistakes
        return total_mistakes / (len(self.y)+0.)
        
    
    
    def predict(self,x):
        return self.root.visit_node(x)


    

In [21]:
def get_test_err(tree):
    # get test error
    num_test_mistakes = 0
    for k in range(len(y_test)):
        x,y = X_test[k,:],y_test[k]
        if y != tree.predict(x):
            num_test_mistakes += 1
    return num_test_mistakes / (len(y_test)+0.)



tree = Tree(X_train,y_train)
tree.print_tree()
print('current train err:', tree.report_train_err())
print('current test err:', get_test_err(tree))


# my first split
best_feat, splitval, set1, set2 = find_best_split(X_train, y_train)
 
left_child = tree.construct_node(set1)
right_child = tree.construct_node(set2)
tree.root.is_leaf = False
tree.leaves.pop(tree.leaves.index(tree.root))
tree.root.add_split_details(splitfeat = best_feat, splitval = splitval)


tree.root.children = [left_child, right_child]
tree.leaves.extend(tree.root.children)
tree.print_tree()
print('one step train err:', tree.report_train_err())
print('one step test err:', get_test_err(tree))

printing tree...
0
, ROOT
, label  0
, LEAF,  nsamples 100, purity 0.53
current train err: 1.0
current test err: 1.0
printing tree...
0
, ROOT
, label  0
, NONLEAF, split 0, val 0.00
1
, parent  0
, label  0
, LEAF,  nsamples 50, purity 0.44
2
, parent  0
, label  0
, LEAF,  nsamples 50, purity 0.62
one step train err: 1.0
one step test err: 1.0
